# automatically generated by the FlatBuffers compiler, do not modify

# namespace: OgTeam1PA1

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ChatMessageTable(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ChatMessageTable()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsChatMessageTable(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ChatMessageTable
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ChatMessageTable
    def User(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ChatMessageTable
    def Password(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ChatMessageTable
    def Receiver(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ChatMessageTable
    def Contents(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def ChatMessageTableStart(builder):
    builder.StartObject(4)

def Start(builder):
    ChatMessageTableStart(builder)

def ChatMessageTableAddUser(builder, user):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(user), 0)

def AddUser(builder, user):
    ChatMessageTableAddUser(builder, user)

def ChatMessageTableAddPassword(builder, password):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(password), 0)

def AddPassword(builder, password):
    ChatMessageTableAddPassword(builder, password)

def ChatMessageTableAddReceiver(builder, receiver):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(receiver), 0)

def AddReceiver(builder, receiver):
    ChatMessageTableAddReceiver(builder, receiver)

def ChatMessageTableAddContents(builder, contents):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(contents), 0)

def AddContents(builder, contents):
    ChatMessageTableAddContents(builder, contents)

def ChatMessageTableEnd(builder):
    return builder.EndObject()

def End(builder):
    return ChatMessageTableEnd(builder)
